services:
  face-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saiv-face-recognition
    ports:
      - "8001:8001"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      MOBILEFACENET_MODEL_PATH: /app/app/models/w600k_mbf.onnx
      FACE_MATCH_THRESHOLD: "0.73"
      FACE_HASH_SIMILARITY_MIN: "0.67"
      FACE_SIM_LOGISTIC_CENTER: "0.70"
      FACE_SIM_LOGISTIC_STEEPNESS: "28.0"
    volumes:
      - ./app/models:/app/app/models:ro
    networks:
      - saiv-network


  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: saiv-otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - saiv-network

networks:
  saiv-network:
    driver: bridge
